### PR TITLE
Add log-out button

### PR DESCRIPTION
**Pull request by EdiOancea**

### CODE REVIEW

**Comment by EdiOancea** [comment]
[Create logout "page"](https://trello.com/c/Poqu0kHD/3-create-logout-page)

**Comment by lgnstn** [comment]
@EdiOancea Please resolve conflicts

**Comment by lgnstn** [comment]
Hey @EdiOancea! New conflicts :(

**Comment by EdiOancea** [comment]
@lgnstn updated

**Review by lgnstn — APPROVED** [review]

**Pull request merged**
